apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
    tier: backend
  name: web
spec:
  ports:
    - port: 80
      nodePort: 30000
      targetPort: 80
  selector:
    app: web
    tier: backend
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
        tier: backend
    spec:
      containers:
        - name: web
          image: local/web:latest
          imagePullPolicy: Never
          # env:
          #   - name: DB_USER
          #     valueFrom:
          #       secretKeyRef:
          #         name: nopw-secret
          #         key: sql_user
          #   - name: DB_PASSWD
          #     valueFrom:
          #       secretKeyRef:
          #         name: nopw-secret
          #         key: sql_password
          #   - name: DB_HOST
          #     valueFrom:
          #       secretKeyRef:
          #         name: nopw-secret
          #         key: sql_host
          ports:
            - name: web
              containerPort: 80
              protocol: TCP
